version: 2
updates:
    - package-ecosystem: 'npm'
      directory: '/'
      schedule:
          interval: 'daily'
          time: '07:00'
          timezone: 'America/New_York'
      open-pull-requests-limit: 25
      labels:
          - "dependencies"
      ignore:
          # rwsdk@0.1.26 requires vite ^6.2.6, cannot upgrade to vite 7.x
          - dependency-name: 'vite'
            versions: ['7.x']
      groups:
          typescript-ecosystem:
              patterns:
                  - 'typescript'
                  - '@typescript-eslint/*'
          vite-ecosystem:
              patterns:
                  - 'vite'
                  - '@vitejs/*'
          testing:
              patterns:
                  - 'vitest'
                  - '@vitest/*'
                  - '@testing-library/*'
                  - 'playwright'
          react-ecosystem:
              patterns:
                  - 'react'
                  - '@types/react*'
                  - 'react-*'
          tanstack:
              patterns:
                  - '@tanstack/*'
          firebase:
              patterns:
                  - 'firebase'
                  - 'firebase-*'
                  - 'react-firebase-*'
      commit-message:
          prefix: 'dependabot'
          include: 'scope'

    - package-ecosystem: 'github-actions'
      directory: '/'
      schedule:
          interval: 'daily'
          time: '07:00'
          timezone: 'America/New_York'
      open-pull-requests-limit: 25
      labels:
          - "dependencies"
      ignore:
          - dependency-name: 'ataylorme/eslint-annotate-action'
      commit-message:
          prefix: 'dependabot'
          include: 'scope'
