overrides:
    '@typescript-eslint/utils': '^8.57.0'
allowBuilds:
    '@firebase/util': false
    '@prisma/client': true
    '@prisma/engines': true
    'esbuild': true
    'prisma': true
    'protobufjs': false
    'sharp': true
    'workerd': true
