# Cleanup PR preview deployments when PR is closed or merged
name: Cleanup Preview

on:
  pull_request:
    types: [closed]

permissions:
  contents: read
  pull-requests: write

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Delete preview version
        uses: cloudflare/wrangler-action@v3.14.1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: versions delete --preview-alias pr-${{ github.event.pull_request.number }} --yes
        continue-on-error: true

      - name: Comment on PR about cleanup
        uses: actions/github-script@v8
        with:
          script: |
            const prNumber = context.issue.number;

            await github.rest.issues.createComment({
              issue_number: prNumber,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `🧹 Preview environment cleaned up (pr-${prNumber}-avalon-analytics)`
            });
        continue-on-error: true
