# Cleanup PR preview deployments when PR is closed or merged
name: Cleanup Preview

on:
  pull_request:
    types: [closed]

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Delete preview worker
        run: |
          npx wrangler delete --name avalon-analytics-pr-${{ github.event.number }} --force
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        continue-on-error: true

      - name: Comment on PR about cleanup
        uses: actions/github-script@v7
        with:
          script: |
            const prNumber = context.issue.number;

            await github.rest.issues.createComment({
              issue_number: prNumber,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `🧹 Preview environment cleaned up (avalon-analytics-pr-${prNumber})`
            });
        continue-on-error: true
