# Jobs that run on merge_group, meaning they must pass before changes land. They also run on pull_request.

on:
    pull_request:
    merge_group:

concurrency:
    group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
    cancel-in-progress: true

jobs:
    lint:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            checks: write
            pull-requests: write
        steps:
            - uses: actions/checkout@v4
            - uses: jdx/mise-action@v2

            - run: just lint-ci
              continue-on-error: true

            - uses: ataylorme/eslint-annotate-action@2.2.0
              if: always()

    format:
        name: Format (Biome)
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: jdx/mise-action@v2

            - run: just format-ci

    typecheck:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: jdx/mise-action@v2
            - run: just typecheck-ci

    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: jdx/mise-action@v2
            - run: just build-ci

    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: jdx/mise-action@v2

            - run: just test-ci

    all-checks:
        name: All checks
        needs: [lint, format, typecheck, build, test]
        runs-on: ubuntu-latest
        steps:
            - name: All checks passed
              run: echo "All checks passed!"
